require("config.options")
vim.g.mapleader = vim.keycode("<Space>")
vim.g.maplocalleader = vim.keycode("<Space>")
local colors = require("util.colors")
local function setup_colorscheme()
  vim.cmd("highlight clear")
  vim.o.background = "dark"
  local hl = function(name, opts)
    vim.api.nvim_set_hl(0, name, opts)
  end
  hl("Added", { fg = colors.green[400] })
  hl("Boolean", { link = "Constant" })
  hl("Changed", { fg = colors.amber[400] })
  hl("Character", { link = "String" })
  hl("Comment", { fg = colors.slate[500], italic = true })
  hl("Conditional", { link = "Statement" })
  hl("Constant", { fg = colors.amber[400] })
  hl("Cursor", { fg = colors.slate[900], bg = colors.slate[50] })
  hl("CursorLine", { bg = colors.slate[800] })
  hl("CursorLineNr", { fg = colors.slate[200], bold = true })
  hl("Delimiter", { fg = colors.slate[300] })
  hl("DiagnosticError", { fg = colors.red[400] })
  hl("DiagnosticHint", { fg = colors.cyan[400] })
  hl("DiagnosticInfo", { fg = colors.blue[400] })
  hl("DiagnosticUnderlineError", { undercurl = true, sp = colors.red[400] })
  hl("DiagnosticUnderlineHint", { undercurl = true, sp = colors.cyan[400] })
  hl("DiagnosticUnderlineInfo", { undercurl = true, sp = colors.blue[400] })
  hl("DiagnosticUnderlineWarn", { undercurl = true, sp = colors.amber[400] })
  hl("DiagnosticWarn", { fg = colors.amber[400] })
  hl("Directory", { fg = colors.blue[400] })
  hl("FloatBorder", { fg = colors.slate[500], bg = colors.slate[800] })
  hl("Function", { fg = colors.blue[400] })
  hl("IncSearch", { fg = colors.slate[900], bg = colors.amber[300] })
  hl("Keyword", { link = "Statement" })
  hl("LineNr", { fg = colors.slate[500] })
  hl("Normal", { fg = colors.slate[200], bg = colors.slate[900] })
  hl("NormalFloat", { fg = colors.slate[200], bg = colors.slate[800] })
  hl("Number", { link = "Constant" })
  hl("Pmenu", { fg = colors.slate[200], bg = colors.slate[800] })
  hl("PmenuSbar", { bg = colors.slate[700] })
  hl("PmenuSel", { fg = colors.slate[100], bg = colors.slate[700] })
  hl("PmenuThumb", { bg = colors.slate[500] })
  hl("PreProc", { fg = colors.cyan[400] })
  hl("Removed", { fg = colors.red[400] })
  hl("Repeat", { link = "Statement" })
  hl("Search", { fg = colors.slate[900], bg = colors.amber[400] })
  hl("Special", { fg = colors.violet[400] })
  hl("Statement", { fg = colors.pink[400] })
  hl("StatusLine", { fg = colors.slate[200], bg = colors.slate[800] })
  hl("StatusLineNC", { fg = colors.slate[500], bg = colors.slate[800] })
  hl("String", { fg = colors.green[400] })
  hl("Type", { fg = colors.cyan[400] })
  hl("Visual", { bg = colors.slate[700] })
  hl("WinSeparator", { fg = colors.slate[700] })
end
setup_colorscheme()
