local colors = require("util.colors")
local hl = function(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end
vim.cmd("highlight clear")
hl("Added", { fg = colors.green[400] })
hl("Changed", { fg = colors.amber[400] })
hl("Character", { link = "String" })
hl("Comment", { fg = colors.slate[400], italic = true })
hl("Constant", { fg = colors.pink[400] })
hl("CursorColumn", { bg = colors.slate[800] })
hl("CursorLine", { bg = colors.slate[800] })
hl("CursorLineNr", { fg = colors.slate[300], bold = true })
hl("Delimiter", { fg = colors.violet[300] })
hl("DiagnosticError", { fg = colors.red[400] })
hl("DiagnosticHint", { fg = colors.slate[300] })
hl("DiagnosticInfo", { fg = colors.blue[400] })
hl("DiagnosticUnderlineError", { undercurl = true, sp = colors.red[400] })
hl("DiagnosticUnderlineHint", { undercurl = true, sp = colors.slate[300] })
hl("DiagnosticUnderlineInfo", { undercurl = true, sp = colors.blue[400] })
hl("DiagnosticUnderlineWarn", { undercurl = true, sp = colors.orange[400] })
hl("DiagnosticWarn", { fg = colors.orange[400] })
hl("Directory", { fg = colors.blue[400] })
hl("FloatBorder", { fg = colors.slate[400], bg = colors.slate[800] })
hl("Function", { fg = colors.teal[200] })
hl("IncSearch", { fg = colors.slate[900], bg = colors.amber[300] })
hl("LineNr", { fg = colors.slate[500] })
hl("Normal", { fg = colors.slate[300] })
hl("NormalFloat", { fg = colors.slate[300], bg = colors.slate[800] })
hl("Operator", { link = "Statement" })
hl("Pmenu", { link = "NormalFloat" })
hl("PmenuSel", { fg = colors.slate[100], bg = colors.slate[700] })
hl("PreProc", { fg = colors.teal[200] })
hl("Removed", { link = "DiagnosticError" })
hl("Search", { fg = colors.slate[900], bg = colors.amber[400] })
hl("Special", { fg = colors.violet[400] })
hl("Statement", { fg = colors.indigo[300] })
hl("StatusLine", { fg = colors.slate[300] })
hl("String", { fg = colors.blue[300] })
hl("Type", { fg = colors.teal[200] })
hl("Visual", { bg = colors.slate[700] })
hl("WinBar", { reverse = false })
hl("WinSeparator", { fg = colors.slate[700] })
-- mini.icons
hl("MiniIconsAzure", { fg = colors.blue[300] })
hl("MiniIconsBlue", { fg = colors.blue[300] })
hl("MiniIconsCyan", { fg = colors.teal[300] })
hl("MiniIconsGreen", { fg = colors.emerald[300] })
hl("MiniIconsGrey", { fg = colors.slate[300] })
hl("MiniIconsOrange", { fg = colors.stone[300] })
hl("MiniIconsPurple", { fg = colors.violet[300] })
hl("MiniIconsRed", { fg = colors.rose[300] })
hl("MiniIconsYellow", { fg = colors.amber[300] })
-- treesitter
hl("@punctuation.bracket", { fg = colors.blue[300] })
hl("@type.builtin", { fg = colors.slate[300], italic = true })
