local colors = require("util.colors")
local hl = function(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end
-- syntax
hl("Comment", { fg = colors.slate[400], italic = true })
hl("Constant", { fg = colors.pink[400] })
hl("Delimiter", { fg = colors.purple[300] })
hl("Special", { fg = colors.purple[400] })
hl("Statement", { fg = colors.indigo[300] })
hl("String", { fg = colors.sky[300] })
hl("Type", { fg = colors.teal[200] })
-- ui
hl("CursorColumn", { bg = colors.slate[700] })
hl("CursorLine", { bg = colors.slate[700] })
hl("CursorLineNr", { bold = true })
hl("FloatBorder", { fg = colors.slate[500] })
hl("IncSearch", { fg = colors.slate[900], bg = colors.amber[300] })
hl("LineNr", { fg = colors.slate[500] })
hl("Normal", { bg = "NONE" })
hl("NormalFloat", { link = "Normal" })
hl("PmenuBorder", { fg = colors.slate[500] })
hl("PmenuSel", { fg = colors.slate[100], bg = colors.slate[700] })
hl("Search", { fg = colors.slate[900], bg = colors.amber[400] })
hl("StatusLine", { bg = "NONE" })
hl("Visual", { bg = colors.slate[700] })
hl("WinBar", { bg = "NONE" })
hl("WinSeparator", { fg = colors.slate[700] })
-- mini.icons
hl("MiniIconsAzure", { fg = colors.blue[300] })
hl("MiniIconsBlue", { fg = colors.blue[300] })
hl("MiniIconsCyan", { fg = colors.teal[300] })
hl("MiniIconsGreen", { fg = colors.emerald[300] })
hl("MiniIconsGrey", { link = "Normal" })
hl("MiniIconsOrange", { fg = colors.orange[300] })
hl("MiniIconsPurple", { fg = colors.purple[300] })
hl("MiniIconsRed", { fg = colors.rose[300] })
hl("MiniIconsYellow", { fg = colors.amber[300] })
-- render-markdown
hl("RenderMarkdownH", { fg = colors.blue[400], bold = true })
hl("RenderMarkdownHBg", { bg = colors.blue[950] })
hl("RenderMarkdownCode", { bg = colors.slate[800] })
hl("RenderMarkdownCodeInline", { fg = colors.sky[300], bg = colors.slate[800] })
-- treesitter
hl("@markup.raw", { fg = colors.slate[200] })
hl("@markup.raw.block", { fg = colors.slate[200] })
hl("@punctuation.bracket", { fg = colors.slate[400] })
hl("@type.builtin", { italic = true })
