vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
local opt = vim.opt
opt.autoread = true
opt.clipboard = "unnamedplus"
opt.cursorcolumn = true
opt.cursorline = true
opt.completeopt = { "menu", "menuone", "noselect" }
opt.expandtab = true
opt.fileencoding = "utf-8"
opt.ignorecase = true
opt.number = true
opt.relativenumber = true
opt.scrolloff = 8
opt.shiftwidth = 2
opt.sidescrolloff = 8
opt.signcolumn = "yes"
opt.smartcase = true
opt.smartindent = true
opt.softtabstop = 2
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.tabstop = 2
opt.termguicolors = true
opt.timeoutlen = 300
opt.undofile = true
opt.updatetime = 250
opt.winbar = "%f"
opt.wrap = false
vim.api.nvim_create_autocmd({ "FocusGained", "BufEnter" }, {
  command = "checktime",
})
