set -g pane-border-style "fg=#99a1af"
set -g pane-active-border-style "#{?#{&&:#{==:#{window_panes},1},#{||:#{==:#{pane_title},#{host}},#{==:#{pane_title},}}},fg=#101828,fg=#74d4ff}"
set -g mode-style "fg=default,bg=#364153"
set -g message-style "fg=default,bg=#364153,fill=#364153"
set -g message-command-style "fg=default,bg=#364153,fill=#364153"
set -g menu-style "fg=#99a1af,bg=#1e2939"
set -g menu-selected-style "fg=default,bg=#364153"
set -g menu-border-style "fg=#99a1af"
set -g popup-border-style "fg=#99a1af"
set -g status-style "fg=#99a1af,bg=default"
set -g status-right "%H:%M %d-%b-%y"
