set -g pane-border-style "fg=#6a7282"
set -g pane-active-border-style "fg=#51a2ff"
set -g mode-style "fg=#f9fafb,bg=#364153"
set -g message-style "fg=#f9fafb,bg=#364153"
set -g message-command-style "fg=#f9fafb,bg=#364153"
set -g menu-style "fg=#99a1af,bg=#1e2939"
set -g menu-selected-style "fg=#f9fafb,bg=#364153"
set -g menu-border-style "fg=#6a7282"
set -g status-style "fg=#99a1af,bg=#1e2939"
set -g status-left " #[fg=#51a2ff,bold]#S "
set -g status-left-length 30
set -g status-right "#[fg=#51a2ff,bold]C-b#[nobold] + #[fg=#99a1af]<#[fg=#51a2ff]|/-#[fg=#99a1af]> split <#[fg=#51a2ff]hjkl#[fg=#99a1af]> move <#[fg=#51a2ff]HJKL#[fg=#99a1af]> resize <#[fg=#51a2ff]z#[fg=#99a1af]> zoom <#[fg=#51a2ff]c#[fg=#99a1af]> tab <#[fg=#51a2ff]x#[fg=#99a1af]> close <#[fg=#51a2ff]?#[fg=#99a1af]> help #{?#{@layout},#[fg=#51a2ff#,nobold]#[fg=#101828#,bg=#51a2ff] #{@layout} ,}"
set -g status-right-length 200
setw -g window-status-format " #I:#W "
setw -g window-status-current-format "#[fg=#f9fafb,bg=#364153] #I:#W "
