set -g pane-border-style "fg=colour4"
set -g pane-active-border-style "fg=colour12"
set -g mode-style "fg=default,bg=#364153"
set -g message-style "fg=default,bg=#364153"
set -g message-command-style "fg=default,bg=#364153"
set -g menu-style "fg=colour8,bg=#1e2939"
set -g menu-selected-style "fg=default,bg=#364153"
set -g menu-border-style "fg=#6a7282"
set -g status-style "fg=colour8,bg=#1e2939"
set -g status-left "#[fg=#101828,bg=colour12,bold] #S #[fg=colour12,bg=#1e2939,nobold]"
set -g status-left-length 30
set -g status-right "#{?#{m:-*,#{e|-:#{client_width},120}},#[fg=colour12#,bold]C-b#[nobold] + #[fg=colour8]<#[fg=colour12]|/-#[fg=colour8]> #[fg=colour8]<#[fg=colour12]←↓↑→#[fg=colour8]> #[fg=colour8]<#[fg=colour12]M-←↓↑→#[fg=colour8]> #[fg=colour8]<#[fg=colour12]z#[fg=colour8]> #[fg=colour8]<#[fg=colour12]c#[fg=colour8]> #[fg=colour8]<#[fg=colour12]x/&#[fg=colour8]> #[fg=colour8]<#[fg=colour12]?#[fg=colour8]> ,#[fg=colour12#,bold]C-b#[nobold] + #[fg=colour8]<#[fg=colour12]|/-#[fg=colour8]> split #[fg=colour8]<#[fg=colour12]←↓↑→#[fg=colour8]> move #[fg=colour8]<#[fg=colour12]M-←↓↑→#[fg=colour8]> resize #[fg=colour8]<#[fg=colour12]z#[fg=colour8]> zoom #[fg=colour8]<#[fg=colour12]c#[fg=colour8]> tab #[fg=colour8]<#[fg=colour12]x/&#[fg=colour8]> close #[fg=colour8]<#[fg=colour12]?#[fg=colour8]> help }"
set -g status-right-length 200
setw -g window-status-format " #I:#W "
setw -g window-status-current-format "#[fg=#1e2939,bg=#364153]#[fg=default,bg=#364153,bold] #I:#W #[fg=#364153,bg=#1e2939,nobold]"
