[tools]
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:anthropics/claude-code" = "2.1.101"
"aqua:ducaale/xh" = "0.25.3"
"aqua:neovim/neovim" = "0.12.1"
"aqua:peco/peco" = "0.6.0"
"aqua:x-motemen/ghq" = "1.10.0"
"aqua:zellij-org/zellij" = "0.44.1"
deno = "2.7.12"
gh = "2.89.0"
go = "1.26.2"
node = "24.14.1"
"npm:@angular/cli" = "21.2.6"
"npm:@fission-ai/openspec" = "1.2.0"
"npm:@googleworkspace/cli" = "0.22.5"
"npm:@ionic/cli" = "7.2.1"
"npm:@openai/codex" = "0.118.0"
"npm:agent-browser" = "0.25.3"
"npm:ccusage" = "18.0.10"
"npm:ntn" = "0.8.0"
pipx = "1.11.1"
# "pipx:browser-use" = "0.12.6"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.5.0"
pnpm = "10.33.0"
python = "3.14.3"
swiftlint = "0.63.2"
uv = "0.11.3"

[settings]
lockfile = true

[env]
