set -as terminal-features "xterm-256color:RGB,xterm*:extkeys"
set -g history-limit 500000
set -g mouse on
set -s extended-keys on

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind x kill-pane
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r Tab if-shell -F "#{==:#{@layout},VERTICAL}" "select-layout even-vertical ; setw @layout HORIZONTAL" "select-layout even-horizontal ; setw @layout VERTICAL"

bind Space display-menu -x C -y C -T "#[align=centre]tmux" \
  "Split |"     "|"   "split-window -h -c '#{pane_current_path}'" \
  "Split -"     "-"   "split-window -v -c '#{pane_current_path}'" \
  "Zoom"        "z"   "resize-pane -Z" \
  "Close pane"  "x"   "kill-pane" \
  "" \
  "Swap prev"   "{"   "swap-pane -U" \
  "Swap next"   "}"   "swap-pane -D" \
  "Rotate"      "C-o" "rotate-window" \
  "Next layout" "Tab" "next-layout" \
  "" \
  "New tab"     "c"   "new-window" \
  "Detach"      "d"   "detach-client"

source-file ~/.config/tmux/themes/zephyr-dark.conf
