set -s extended-keys on
set -as terminal-features "xterm*:extkeys"
set -g focus-events on
set -g mouse on

set -g base-index 1
set -gw pane-base-index 1

set -gw mode-keys vi

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind -n M-Left select-pane -L
bind -n M-Down select-pane -D
bind -n M-Up select-pane -U
bind -n M-Right select-pane -R

bind -r M-Left resize-pane -L
bind -r M-Down resize-pane -D
bind -r M-Up resize-pane -U
bind -r M-Right resize-pane -R

bind x kill-pane
bind & kill-window

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

source-file ~/.config/tmux/themes/zephyr-dark.conf
