name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mise:
    runs-on: macos-latest
    timeout-minutes: 5
    env:
      MISE_CONFIG_FILE: ${{ github.workspace }}/src/.config/mise/config.toml
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@94c60b39bc2d90ab2f9bab27f38d3cc4812c1834 # v5.1.0
      - run: uv sync --locked
