[tools]
deno = "2.4.0"
node = "22.17.0"
"npm:@anthropic-ai/claude-code" = "1.0.43"
"npm:@google/gemini-cli" = "0.1.9"
"npm:pnpm" = "10.12.4"
python = "3.13.5"
uv = "0.7.19"

[env]

[settings]
idiomatic_version_file_enable_tools = ["python"]
