[tools]
deno = "2.3.1"
node = "22.15.0"
"npm:pnpm" = "10.10.0"
python = "3.13.3"
uv = "0.6.16"

[env]

[tasks.zshrc]
run = "cp ~/dotfiles/.zshrc ~/.zshrc"

[tasks."zshrc:dump"]
run = "cp ~/.zshrc ~/dotfiles/.zshrc"

[tasks.gitconfig]
run = "rsync -au ~/dotfiles/.config/.gitconfig ~/"

[tasks."gitconfig:dump"]
run = "rsync -au ~/.gitconfig ~/dotfiles/.config/"

[tasks.gitignore]
run = "rsync -au ~/dotfiles/.config/git/ignore ~/.config/git/"

[tasks."gitignore:dump"]
run = "rsync -au ~/.config/git/ignore ~/dotfiles/.config/git/"

[tasks.mise]
run = "rsync -au ~/dotfiles/.config/mise/config.toml ~/.config/mise/"

[tasks."mise:dump"]
run = "rsync -au ~/.config/mise/config.toml ~/dotfiles/.config/mise/"

[tasks."code:settings_json"]
run = "rsync -au ~/dotfiles/.vscode/settings.json ~/Library/Application\\ Support/Code/User/"

[tasks."code:settings_json:dump"]
run = "rsync -au ~/Library/Application\\ Support/Code/User/settings.json ~/dotfiles/.vscode/"

[tasks.all]
depends = ["zshrc", "gitignore", "mise", "code:settings_json"]

[tasks."all:dump"]
depends = [
  "zshrc:dump",
  "gitignore:dump",
  "mise:dump",
  "code:settings_json:dump",
]

[tasks."macos:defaults"]
run = "zsh ~/dotfiles/themes/defaults.sh"
